### ISSUE TITLE
Tidy benchmarking

### ISSUE THREAD

**Issue by ElliottKasoar** [Cambridge-ICCS/FTorch-benchmarks#24]
A general pass of the repo is needed to tidy up, potentially including:

- [x] Ensuring all unused variables are removed/used
- [x] Add functioning assertions to all benchmarks
- [x] Remove code that is no longer needed (#18?)
- [x] Refactor shared code (e.g. between assert functions in #22)
- [x] Ensure changes in FTorch are reflected in code here
- [x] Restructure code into separate folders, as mentioned in #20

**Comment by TomMelt** [comment]
when we restructure code into folders, the following source files need to go together.

* `cg_drag_forpy.f90`
* `cg_drag_torch.f90`
* `benchmarker_forpy.f90`
* `benchmarker_torch.f90`

These test the structure of gravity wave drag routines in MIMA. Possibly rename module files to make it clear they are modules.
